.gitignore
README.md
Vagrantfile
ansible/roles/mbbox-dev/defaults/main.yml
ansible/roles/mbbox-dev/files/.bashrc
ansible/roles/mbbox-dev/files/mbbox-dev.yml
ansible/roles/mbbox-dev/files/motd
ansible/roles/mbbox-dev/files/postgresql-ephemeral-template.json
ansible/roles/mbbox-dev/handlers/main.yml
ansible/roles/mbbox-dev/tasks/main.yml
ansible/roles/mbbox-dev/tasks/openshift.yml
ansible/roles/mbbox-dev/tasks/rabbitmq.yml
ansible/vagrant-playbook.yml
components/identity/buildconfig.yml
components/identity/configmap.yml
components/koji_hub/buildconfig.yml
components/koji_hub/configmap.yml
components/koji_hub/deploymentconfig.yml

Vagrant environment sets up OpenShift environment for development.
The liveliness and readiness probe for koji is still not working.
This causes error to be thrown at the end of the mbbox script.
Koji still needs some work, but this environment should be enough to
start working with this script locally.

Add vagrant environment

---

ansible/roles/openshift-osdk/defaults/main.yml
ansible/roles/openshift-osdk/files/motd
ansible/roles/openshift-osdk/tasks/operator-sdk.yml
mbox-operator/.yamllint
mbox-operator/README.md
mbox-operator/build/Dockerfile
mbox-operator/build/test-framework/Dockerfile
mbox-operator/build/test-framework/ansible-test.sh
mbox-operator/deploy/crds/apps.fedoraproject.org_mboxes_crd.yaml
mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbox_cr.yaml
mbox-operator/deploy/operator.yaml
mbox-operator/deploy/role.yaml
mbox-operator/deploy/role_binding.yaml
mbox-operator/deploy/service_account.yaml
mbox-operator/molecule/default/asserts.yml
mbox-operator/molecule/default/converge.yml
mbox-operator/molecule/default/molecule.yml
mbox-operator/molecule/default/prepare.yml
mbox-operator/molecule/test-cluster/converge.yml
mbox-operator/molecule/test-cluster/molecule.yml
mbox-operator/molecule/test-local/converge.yml
mbox-operator/molecule/test-local/molecule.yml
mbox-operator/molecule/test-local/prepare.yml
mbox-operator/roles/mbox/README.md
mbox-operator/roles/mbox/defaults/main.yml
mbox-operator/roles/mbox/handlers/main.yml
mbox-operator/roles/mbox/meta/main.yml
mbox-operator/roles/mbox/tasks/main.yml
mbox-operator/roles/mbox/vars/main.yml
mbox-operator/watches.yaml

Fixes: #15
Adds the basic structure for the mbox ansible based operator.
It will create a memcached deployment object when a mbox custom resource is created just for bootstrap/example purposes for the first PR.
```
kubectl apply -f deploy/crds/deploy/crds/apps.fedoraproject.org_mboxes_crd.yaml
kubectl apply -f deploy/
```
Checking if the operator is successfully running:
```
$ kubectl get pods -w
NAME                              READY   STATUS    RESTARTS   AGE
mbox-operator-6867d56dd4-q2ddq   2/2     Running   0          11m
```
Creating a mbox resource:
```
kubectl apply -f deploy/crds/apps.fedoraproject.org_v1alpha1_mbox_cr.yaml
```
Editing the `size` property from the mbox resource (`kubectl edit mbox/example-mbox`) will reflect on memcached replicas and deleting it should delete the …

mbox operator project

---

mbox-operator/deploy/cluster_role_binding.yaml
mbox-operator/deploy/operator.yaml.j2
mbox-operator/molecule/test-cluster/converge.yml
mbox-operator/molecule/test-cluster/destroy.yml
mbox-operator/molecule/test-cluster/molecule.yml
mbox-operator/molecule/test-cluster/prepare.yml

Adds basic structure for the test-cluster molecule case:
```sh
molecule test -s test-cluster
```
It doesn't build an image since it should pull an external published image to run al tests.
ping @Zlopez

test-cluster

---

.zuul.yaml
ci/test-cluster.yml
ci/test-local.yml
mbox-operator/molecule/test-cluster/destroy.yml
mbox-operator/molecule/test-cluster/prepare.yml

Because jenkins-fedora-apps.apps.ci.centos.org doesn't have working cico nodes yet and we need a VM for spawning the kubernetes cluster, I opted to try to prototype the PR check on Zuul.
Closes #22

Added config for Zuul CI

---

mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojihub_cr.yaml
mbox-operator/molecule/default/asserts/koji-hub.yml
mbox-operator/roles/koji-hub/defaults/main.yml
mbox-operator/roles/koji-hub/tasks/cert.yml
mbox-operator/roles/koji-hub/tasks/main.yml
mbox-operator/roles/koji-hub/templates/configmap.yml.j2
mbox-operator/roles/koji-hub/templates/deployment.yml.j2
mbox-operator/roles/koji-hub/templates/ingress.yml.j2

fixes #26
This PR enables TLS for both internal service and ingress.
Run one of the following commands:
* `operator-sdk test local`
* `molecule test -s test-local`
* Change "host" value in mbkojihub mbox CR to the correct app host;
* Build an image, push it and  change the image name in `deploy/operator.yaml`
* Optional: enable ingress addon if using minikube
* Deploy both operator and CR;
* Wait for your ingress to be available (aka show an address) and test it with curl: `curl -k https://$ADDR/kojihub`

tls support

---

.gitignore
README.md
docs/Makefile
docs/make.bat
docs/source/conf.py
docs/source/contributing.rst
docs/source/index.rst

fixes #31 
This PR creates the basic structure for the operator documentation.
* Added a doc folder containing a sphinx project in rst format;
* Run `make html` to build its html documentation within the `docs` folder;

docs setup

---

images/koji-hub/Dockerfile
images/koji-hub/entrypoint.sh
images/koji-hub/readiness.sh
mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojihub_cr.yaml
mbox-operator/roles/koji-hub/defaults/main.yml
mbox-operator/roles/koji-hub/tasks/cert.yml
mbox-operator/roles/koji-hub/templates/deployment.yml.j2

fixes #59 
* re-factors tls cert generation to include CA extensions
* adds psql schema import in koji-hub image
* fixes readiness koji-hub script
NOTE: you will need to build both koji-hub and operator images on your own and change the image reference before deployment or use the following built images:
* quay.io/lrossett/mbox-operator:latest
* quay.io/lrossett/koji-hub:latest
* Deploy mbox operator and kojihub cr
* "ssh" into the koji-hub pod: `k exec -it koji-hub-6bff9b7544-4jwq7 -- /bin/bash`
* cd into `/tmp` and run the following commands:
* `openssl genrsa -out client.key 4096`
* `openssl req -new -key client.key -out client.csr` (skip everything but common name which should be the desired koji username such as "mboxdev")
* `openssl x509 -req -in client.csr -CA /etc/cacert/cert …

tls ca fix

---

docs/source/index.rst
docs/source/user-guide/index.rst
docs/source/user-guide/koji-hub.rst

Fixes #28
* Adds koji-hub crd sphinx docs
* cd into `docs`
* run `make html`
* access the docs: `docs/build/html/index.html` and a user guide/koji-hub section should be available

koji-hub crd docs

---

.zuul.yaml
ci/test-default.yml
mbox-operator/molecule/default/molecule.yml
mbox-operator/molecule/test-cluster/molecule.yml

Made the default molecule test suite to run lint, removed lint from cluster test, added the default test to CI.
Te default test suite was not working anyway, and splitting it sounds useful for CI (i.e. we will see more failures faster, instead of "lint failed" - "push" - "test cluster failed", they will run in paralell)

Made the default molecule test suite to run lint

---

ansible/roles/mbbox-dev/tasks/main.yml

Adding these packages will allow us to build documentation inside vagrant machine.

Update vagrant to support documentation building

---

docs/source/contributing.rst

Update contribution guide

---

mbox-operator/build/Dockerfile
mbox-operator/roles/koji-hub/defaults/main.yml
mbox-operator/roles/koji-hub/tasks/cert.yml
mbox-operator/roles/koji-hub/tasks/main.yml

fixes #61 
* adds admin user to psql
* grants admin user admin perms
* creates an admin client certificate
* check if a new record was added in both users and user_perms table after koji-hub is deployed
* check if koji-hub admin client cert was properly created

Issue 61 user setup

---

.zuul.yaml
ci/test-default.yml
ci/test-local.yml

Previously we had problem starting up the kind cluster in the time-limit.
Medium vm should help.
Additionally, we shouldn't need the full vm for docs and linting :-)

Adding test-local back again

---

docs/source/user-guide/koji-builder.rst
mbox-operator/Makefile
mbox-operator/build/Dockerfile
mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojibuilder_cr.yaml
mbox-operator/deploy/operator.yaml.j2
mbox-operator/molecule/default/asserts/koji-builder.yml
mbox-operator/roles/koji-builder/defaults/main.yml
mbox-operator/roles/koji-builder/meta/main.yml
mbox-operator/roles/koji-builder/tasks/cert.yml
mbox-operator/roles/koji-builder/tasks/main.yml
mbox-operator/roles/koji-lib/library/koji_host.py

fixes #61 
* Setups a koji-hub host when a koji-builder cr is created from the operator using the admin cert
* uses a different cert for koji-buider with no admin access
* builder CN needs to be the same value used as builder host
* Run tests
* Deploy builder + hub and koji-builder should not crash

koji-builder add host

---

mbox-operator/roles/koji-builder/templates/deployment.yml.j2

fixes #71 
* Adds a liveness probe check for koji-builder
* Run tests or deployment - it should work as usual
I couldn't find anything for "readiness check" as checking if kojid is running is the only thing that can be validated - open to suggestions here.

builder checks

---

.zuul.yaml

There is a problem with module repos, might be a container issue.

Switching the linting ci job from container back to VM

---

mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojira_cr.yaml
mbox-operator/molecule/default/asserts/kojira.yml
mbox-operator/roles/kojira/defaults/main.yml
mbox-operator/roles/kojira/tasks/cert.yml
mbox-operator/roles/kojira/tasks/main.yml
mbox-operator/roles/kojira/templates/kojira.configmap.yaml.j2

This adds the certificates for Kojira. This is done similar way as
in koji-builder.
Closes #35.

Add certificates for Kojira

---

mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsfrontend_cr.yaml
mbox-operator/molecule/default/asserts/mbs-frontend.yml
mbox-operator/roles/mbs-frontend/defaults/main.yml
mbox-operator/roles/mbs-frontend/tasks/main.yml
mbox-operator/roles/mbs-frontend/templates/.keep
mbox-operator/roles/mbs-frontend/templates/mbs-configmap.yaml.j2
mbox-operator/roles/mbs-frontend/templates/mbs-frontend.configmap.yaml.j2

Add two configmaps for mbs-frontend, one contains configuration specific
for the mbs-frontend, second contains shared configuration for
mbs-frontend and mbs-backend.
Closes #44

Add configmap for mbs-frontend

---

mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbox_cr.yaml
mbox-operator/molecule/default/asserts/mbox.yml
mbox-operator/molecule/default/converge/converge_mbox.yml
mbox-operator/molecule/default/converge/tasks/mbox.yml
mbox-operator/molecule/test-cluster/converge.yml
mbox-operator/molecule/test-local/converge.yml
mbox-operator/roles/mbox/defaults/main.yml
mbox-operator/roles/mbox/tasks/cert.yml
mbox-operator/roles/mbox/tasks/main.yml

Fixes #33 
* Mbox cr creates a ca secret and pvc object to be used by other components;
* Both ca secret and pvc are not created if already present using the same name in the same namespace.
* Run tests
The usage of those shared resources on other components will be implemented in other PRs.

mbox secret and pvc

---

mbox-operator/molecule/test-local/destroy.yml
mbox-operator/molecule/test-local/molecule.yml

*  Add destroy playbook for local tests
* Check if the `docker volumes ls` is empty after running `operator-sdk test local`

Add docker prune to local destroy sequence

---

mbox-operator/roles/koji-hub/tasks/main.yml

Fixes #108 
* uses exiting PVCs for both httpd and shared mnt volumes if already created 
* run tests and deployment

use existing volume

---

images/koji-hub/Dockerfile

* Changes the url of `fedmsg-koji-plugin.py` since the ansible repository was moved to pagure;
* Check if the new url is correct
Just a change of URLs since the old url was returning a 404 error.

using koji plugin url from pagure

---

docs/source/user-guide/koji-hub.rst
mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojihub_cr.yaml
mbox-operator/molecule/default/asserts/koji-hub.yml
mbox-operator/roles/koji-hub/defaults/main.yml
mbox-operator/roles/koji-hub/tasks/cert.yml
mbox-operator/roles/koji-hub/templates/configmap.yml.j2
mbox-operator/roles/koji-hub/templates/deployment.yml.j2

* adds a koji-web client cert for koji-web ssl auth in koji-hub
* run tests
There is an upstream koji PR that needs to be merged for koji-web work with certs: https://pagure.io/koji/pull-request/2450
Please change the image of koji-hub to `quay.io/lrossett/koji-hub:patch for the web UI validation if needed while that PR is not merged and available as a RPM update.

kojiweb cert support

---

docs/source/user-guide/koji-builder.rst
mbox-operator/config/samples/apps_v1alpha1_mbkojibuilder.yaml
mbox-operator/roles/koji-builder/defaults/main.yml
mbox-operator/roles/koji-builder/tasks/main.yml
mbox-operator/roles/koji-hub/tasks/main.yml

* Uses fully qualified name for services when doing API calls from the operator pod;
* Uses fully qualified name for services when running PSQL queries from the operator pod;
* Split `koji_hub_url` into two new properties for the koji-builder CR (`koji_host` and `koji_port`);
* Documentation changes due to CRD changes. 
* Run tests or a VM deployment

using full qualified service name for api calls

---

components/kerberos/0-service.yaml
components/kerberos/1-configmap.yaml
components/kerberos/2-deployment.yaml
components/kerberos/README.md
images/kerberos/Dockerfile

This commit adds everything that is need to build the working kerberos
container and deploy it in kubernetes cluster.
Closes #140
* Add kerberos Dockerfile
* Add kerberos configmap
* Add kerberos deployment
* Add kerberos service
* `cd components/kerberos`
* `kubectl apply -f .`
* `kubectl exec -it <kerberos pod> -- kinit` (default password is `admin`)
* No error thrown
In minikube you need to do the following to let verification steps to work:
* `minikube ssh`
* `sudo ip link set docker0 promisc on`

Add kerberos deployment

---

components/kerberos/1-configmap.yaml
components/kerberos/2-deployment.yaml
mbox-operator/molecule/default/converge.yml

Prepare test environment for mbbox components to be tested with
kerberos.
Fixes #147
* Fix kadmin service in kerberos container
* Use quay.oi/fedora/kerberos repository for image
* Deploy kerberos in molecule tests
* Make kerberos domain more general (don't use namespace specific)
* `molecule converge -s test-local`
* `docker exec -it kind-test-local bash`
* `kubectl config set-context --current --namespace=osdk-test`
* `kubectl exec -it <kerberos_pod> -- kinit`
For verification steps to work, you need to run `sudo ip link set docker0 promisc on` in molecule test container

Add kerberos to molecule tests
