- ansible/roles/openshift-osdk/defaults/main.yml
> Update operator-sdk version in vagrant

- ansible/roles/openshift-osdk/tasks/operator-sdk.yml
> Add kubectl and ingress addon to vagrant

- .zuul.yaml
- ci/test-docs.yml
> doc testing

- images/kojira/Dockerfile
- images/kojira/entrypoint.sh
fixes #38 
* adds kojira container files
> kojira image files

- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojira_cr.yaml
- mbox-operator/molecule/default/asserts/kojira.yml
- mbox-operator/roles/kojira/defaults/main.yml
- mbox-operator/roles/kojira/tasks/main.yml
- mbox-operator/roles/kojira/templates/.keep
- mbox-operator/roles/kojira/templates/kojira.configmap.yaml.j2
fixes #34 
* kojira configmap params 
* adds kojira configmap as a template
* provisions it in kubernetes
* Run tests or cluster deployment
> kojira configmap

- images/mbs-backend/Dockerfile
- images/mbs-backend/entrypoint.sh
- images/mbs-backend/mbs-scheduler.py
fixes #43 
* mbs backend image files
> mbs-backend image files

- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojira_cr.yaml
- mbox-operator/molecule/default/asserts/kojira.yml
- mbox-operator/roles/kojira/defaults/main.yml
- mbox-operator/roles/kojira/tasks/main.yml
- mbox-operator/roles/kojira/templates/kojira.deployment.yaml.j2
fixes: #36 
* Adds kojira deployment
* Mounts shared mnt volume from koji-hub in kojira pod
* run tests or deployment
> kojira deployment

- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsbackend_cr.yaml
- mbox-operator/molecule/default/asserts/mbs-backend.yml
- mbox-operator/roles/mbs-backend/defaults/main.yml
- mbox-operator/roles/mbs-backend/tasks/cert.yml
- mbox-operator/roles/mbs-backend/tasks/main.yml
fixes: #40 
* creates a koji-hub client cert for mbs-backend integration
* mbs-backend cert tests
* run tests
> Issue 40 mbs client cert

- images/mbs-frontend/Dockerfile
- images/mbs-frontend/entrypoint.sh
- images/mbs-frontend/mbs.wsgi
Implements part of the acceptance criteria for #48
> Add mbs-frontend image

- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsbackend_cr.yaml
- mbox-operator/molecule/default/asserts/mbs-backend.yml
- mbox-operator/roles/mbs-backend/defaults/main.yml
- mbox-operator/roles/mbs-backend/tasks/cert.yml
- mbox-operator/roles/mbs-backend/tasks/main.yml
- mbox-operator/roles/mbs-backend/templates/deployment.yaml.j2
fixes #41 
* adds mbs backend deployment
* Run tests
> mbs-backend deployment

- docs/source/user-guide/mbs-backend.rst
First attempt at the docs-file.
Might need few additional entries for the deployment part of the CR.
> Added a docs file for mbmbsmackend cr file.

- docs/source/user-guide/koji-builder.rst
- docs/source/user-guide/koji-hub.rst
- docs/source/user-guide/kojira.rst
- docs/source/user-guide/mbs-backend.rst
- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojibuilder_cr.yaml
- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojihub_cr.yaml
- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojira_cr.yaml
- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsbackend_cr.yaml
- mbox-operator/roles/koji-builder/defaults/main.yml
- mbox-operator/roles/koji-builder/tasks/main.yml
- mbox-operator/roles/koji-hub/defaults/main.yml
- mbox-operator/roles/koji-hub/tasks/main.yml
- mbox-operator/roles/kojira/defaults/main.yml
- mbox-operator/roles/kojira/tasks/main.yml
- mbox-operator/roles/mbs-backend/defaults/main.yml
- mbox-operator/roles/mbs-backend/tasks/main.yml
Fixes #58
* "mbox" property for components
* shared pvc usage based on mbox config for all backend components
* deploy the operator
* deploy the mbox cr
* uncomment the commented "mbox" line for each backend cr and create it
* check if components are running successfully
> shared volume

- docs/source/user-guide/mbs-frontend.rst
Closes #47 
* Add documentation of the CRD variables for MSB Frontend
* Docs tests must succeed
> Add documentation to mbs-frontend

- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsfrontend_cr.yaml
- mbox-operator/molecule/default/asserts/mbs-frontend.yml
- mbox-operator/roles/mbs-frontend/defaults/main.yml
- mbox-operator/roles/mbs-frontend/tasks/main.yml
- mbox-operator/roles/mbs-frontend/templates/ingress.yml.j2
- mbox-operator/roles/mbs-frontend/templates/service.yml.j2
Closes #49 
* Add ingress configuration
* Add service configuration
* Add related vars
* Asserts for both ingress and service configurations
> Add service configuration for MBS frontend

- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsbackend_cr.yaml
- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsfrontend_cr.yaml
- mbox-operator/molecule/default/asserts/mbs-frontend.yml
- mbox-operator/molecule/default/converge/tasks/mbs-frontend.yml
- mbox-operator/roles/mbs-backend/tasks/main.yml
- mbox-operator/roles/mbs-frontend/defaults/main.yml
- mbox-operator/roles/mbs-frontend/tasks/main.yml
- mbox-operator/roles/mbs-frontend/templates/deployment.yaml.j2
- mbox-operator/roles/mbs-frontend/templates/mbs-frontend.configmap.yaml.j2
Fixes #49
Tests should pass.
Not sure if fixes #46 or if that was part of #90
> Added the mbs-frontend deployment.

- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbmbsfrontend_cr.yaml
- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbox_cr.yaml
- mbox-operator/molecule/default/converge/tasks/mbox.yml
- mbox-operator/roles/koji-builder/tasks/cert.yml
- mbox-operator/roles/koji-builder/tasks/main.yml
- mbox-operator/roles/koji-hub/tasks/cert.yml
- mbox-operator/roles/koji-hub/tasks/main.yml
- mbox-operator/roles/kojira/tasks/cert.yml
- mbox-operator/roles/kojira/tasks/main.yml
- mbox-operator/roles/mbox/defaults/main.yml
- mbox-operator/roles/mbox/tasks/main.yml
- mbox-operator/roles/mbs-backend/tasks/cert.yml
- mbox-operator/roles/mbs-backend/tasks/main.yml
- mbox-operator/roles/mbs-frontend/defaults/main.yml
- mbox-operator/roles/mbs-frontend/tasks/cert.yml
- mbox-operator/roles/mbs-frontend/tasks/main.yml
Fixes #57 
* uses shared certs from mbox config if "mbox" is set
* uses shared psql secret name from mbox config if set
* runt test or full deployment
*
> shared certs + shared psql secret

- docs/source/deployment-guide.rst
- docs/source/index.rst
- docs/source/user-guide/index.rst
- mbox-operator/Makefile
Part of #96
* Add deployment documentaiton 
* Docs build is successful
* Documentation is rendered without issue
* Links in the deployment guide are working
I'm not sure about the need of admin rights for RBAC. @odra Could you confirm this?
> Add deployment guide

- docs/source/deployment-guide.rst
Fixes #96 
* Fix rendering issues for code blocks 
* docs are build
Code block without specified syntax formatter is not rendered correctly, this will fix it
> Fix rendering issues

- ci/test-docs.yml
- docs/source/user-guide/mbox.rst
* fixes table code
* fails test-docs job if sphinx throws a warning
* force an error and run `make html SPHINXOPTS='-W' (should return a non-zero rc)
> fail docs buid command

- ci/test-local.yml
* specify all pip package versions
* ci job should work
> specific pip lib versions

- docs/source/user-guide/koji-hub.rst
- mbox-operator/deploy/crds/apps.fedoraproject.org_v1alpha1_mbkojihub_cr.yaml
- mbox-operator/deploy/role.yaml
- mbox-operator/roles/koji-hub/tasks/main.yml
- mbox-operator/roles/koji-hub/templates/openshift-route.yml.j2
Fixes #111 
* Adds openshift route support;
* Adds a new `ingress_backend` type for openshift.
* Run tests;
* Deploy on openshift
Using openshift with local tests won't work since it uses raw kuberetes api-server.
> openshift route support

- components/rabbitmq/1-app.secret.yaml
- components/rabbitmq/playbook.yml
- mbox-operator/config/samples/apps_v1alpha1_mbkojihub.yaml
- mbox-operator/molecule/default/converge.yml
- mbox-operator/roles/koji-hub/defaults/main.yml
- mbox-operator/roles/koji-hub/tasks/main.yml
- mbox-operator/roles/koji-hub/templates/deployment.yml.j2
* uses a secret instead of a configmap for rabbitmq cert and key storage;
* roles and tests updated;
* run tests
> rabbitmq secret

- mbox-operator/roles/koji-builder/tasks/cert.yml
- mbox-operator/roles/kojira/tasks/cert.yml
* checks for for existing client certs early on cert.yml
* do not copy "key" file from the CA secret if an existing client secret already exists
* run tests
> fixing existing client cert code

- mbox-operator/molecule/default/tasks/mbkojihub_test.yml
- mbox-operator/roles/koji-hub/tasks/main.yml
- mbox-operator/roles/koji-hub/templates/pvc.yml.j2
* adds `pvc_mode` for koji-hub PVC template;
* sets shared volume do use ReadWriteMany mode;
* tests updated.
* run tests
> pvc_mode var + RWM mode for shared koji volume

- images/koji-hub/Dockerfile
- images/kojira/Dockerfile
- images/mbs-backend/Dockerfile
- images/mbs-frontend/Dockerfile
Fixes #
* updated the base image for each Dockerfile
* run tests
> using latest base images

- .github/ISSUE_TEMPLATE/user-story.md
* Remove DoD from user story
* Add description label.
DoD should be defined for the whole team, not for every user story.
> Update user story template

- ci/roles/openshift-osdk/files/motd
- docs/source/contributing.rst
> Document the docker minikube issue

- docs/source/contributing.rst
* Little optimization of debugging process
> Optimize debugging process
